# -*- coding: utf-8 -*-
"""534388_Aulia Fathus Tsani_Assignment 2 Deep Learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l60se7lpJ0Mjz4u0AZFoNo3uXg8iraZl

# Assignment 2 — Learning Strategy
**Mata Kuliah:** Pembelajaran Mesin Mendalam (Deep Learning)

**Nama :** Aulia Fathus Tsani

**NIM  :** 24/534388/PA/22661

Notebook ini terdiri dari dua bagian:
1. **Replikasi kode** klasifikasi MNIST dari slide *Learning Strategy* (halaman 14–23)
2. **Eksperimen** penerapan L1 regularization, L2 regularization, Dropout, Early Stopping, dan kombinasi L1+Dropout — masing-masing dilengkapi `model.summary()`, performa, dan grafik loss

## 0. Import Library
"""

import numpy as np
import matplotlib.pyplot as plt

import keras
from keras.models import Sequential
from keras.layers import Flatten, Dense, Dropout, Input
from keras import regularizers
from keras.callbacks import EarlyStopping

"""## 1. Replikasi Kode (Slide 14–23)
### 1.1 Load Data
"""

from keras.datasets import mnist

(X_train, y_train), (X_test, y_test) = mnist.load_data()

X_train = X_train.reshape(-1, 28, 28, 1)
X_test = X_test.reshape(-1, 28, 28, 1)
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train /= 255
X_test /= 255

y_train = keras.utils.to_categorical(y_train, 10)
y_test = keras.utils.to_categorical(y_test, 10)

print('X_train', X_train.shape)
print('X_test', X_test.shape)

"""### 1.2 Define Model"""

model1 = Sequential()
model1.add(Input(shape=(28, 28, 1)))
model1.add(Flatten())
model1.add(Dense(64, activation='relu'))
model1.add(Dense(10, activation='softmax'))

"""### 1.3 Compile Model, Fit Model, Save Model, and Evaluate Model"""

model1.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['acc'])

history1 = model1.fit(
    X_train, y_train,
    epochs=10, batch_size=100,
    validation_data=(X_test, y_test)
)

model1.save('my_model1.h5')
model1.evaluate(X_test, y_test)

"""### 1.4 Visualize Model Evaluation"""

epochs = range(1, len(history1.history['loss']) + 1)
loss1 = history1.history['loss']
val_loss1 = history1.history['val_loss']

plt.plot(epochs, loss1, 'r', label='training loss ANN')
plt.plot(epochs, val_loss1, 'b', label='validation loss ANN')
plt.title('Baseline Model - Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.show()

model1.summary()

"""### 1.5 Load Model and Prediction"""

from keras.models import load_model

model_simpan = load_model('my_model1.h5')
pred = model_simpan.predict(X_test)
print('label actual:', np.argmax(y_test[30]))
print('label prediction:', np.argmax(pred[30]))

"""## 2. Eksperimen
Fungsi bantu berikut dipakai berulang di setiap skenario agar konsisten: membangun model, melatih, menampilkan `model.summary()`, mengevaluasi, dan menampilkan grafik loss.
"""

def run_scenario(name, build_fn, callbacks=None, epochs=10, batch_size=100):
    print(f"=== {name} ===")
    model = build_fn()
    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['acc'])
    history = model.fit(
        X_train, y_train,
        epochs=epochs, batch_size=batch_size,
        validation_data=(X_test, y_test),
        callbacks=callbacks or []
    )
    model.summary()
    loss, acc = model.evaluate(X_test, y_test)
    print(f"Akurasi Testing {name}:", acc)

    ep = range(1, len(history.history['loss']) + 1)
    plt.figure()
    plt.plot(ep, history.history['loss'], 'r', label='training loss')
    plt.plot(ep, history.history['val_loss'], 'b', label='validation loss')
    plt.title(f'{name} - Loss')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.legend()
    plt.show()

    return model, history, loss, acc

"""### 2a. L1 Regularization
Rate L1 didefinisikan sendiri: `L1_RATE = 0.0001`
"""

L1_RATE = 0.0001

def build_l1():
    m = Sequential()
    m.add(Input(shape=(28, 28, 1)))
    m.add(Flatten())
    m.add(Dense(64, activation='relu', kernel_regularizer=regularizers.l1(L1_RATE)))
    m.add(Dense(10, activation='softmax', kernel_regularizer=regularizers.l1(L1_RATE)))
    return m

model_l1, history_l1, loss_l1, acc_l1 = run_scenario('2a - L1 Regularization', build_l1)

"""### 2b. L2 Regularization
Rate L2 didefinisikan sendiri: `L2_RATE = 0.0001`
"""

L2_RATE = 0.0001

def build_l2():
    m = Sequential()
    m.add(Input(shape=(28, 28, 1)))
    m.add(Flatten())
    m.add(Dense(64, activation='relu', kernel_regularizer=regularizers.l2(L2_RATE)))
    m.add(Dense(10, activation='softmax', kernel_regularizer=regularizers.l2(L2_RATE)))
    return m

model_l2, history_l2, loss_l2, acc_l2 = run_scenario('2b - L2 Regularization', build_l2)

"""### 2c. Dropout
Rate Dropout didefinisikan sendiri: `DROPOUT_RATE = 0.3`
"""

DROPOUT_RATE = 0.3

def build_dropout():
    m = Sequential()
    m.add(Input(shape=(28, 28, 1)))
    m.add(Flatten())
    m.add(Dense(64, activation='relu'))
    m.add(Dropout(DROPOUT_RATE))
    m.add(Dense(10, activation='softmax'))
    return m

model_dropout, history_dropout, loss_dropout, acc_dropout = run_scenario('2c - Dropout', build_dropout)

"""### 2d. Early Stopping
`EarlyStopping(monitor='val_loss', patience=2, restore_best_weights=True)`, dengan `epochs` maksimum dinaikkan (mis. 30) agar early stopping punya kesempatan berhenti lebih awal.
"""

def build_es():
    m = Sequential()
    m.add(Input(shape=(28, 28, 1)))
    m.add(Flatten())
    m.add(Dense(64, activation='relu'))
    m.add(Dense(10, activation='softmax'))
    return m

es_callback = EarlyStopping(monitor='val_loss', patience=2, restore_best_weights=True)

model_es, history_es, loss_es, acc_es = run_scenario(
    '2d - Early Stopping', build_es, callbacks=[es_callback], epochs=30
)
print('Jumlah epoch aktual sebelum berhenti:', len(history_es.history['loss']))

"""### 2e. L1 Regularization + Dropout
Menggabungkan `L1_RATE` dan `DROPOUT_RATE` yang sudah didefinisikan di atas.
"""

def build_l1_dropout():
    m = Sequential()
    m.add(Input(shape=(28, 28, 1)))
    m.add(Flatten())
    m.add(Dense(64, activation='relu', kernel_regularizer=regularizers.l1(L1_RATE)))
    m.add(Dropout(DROPOUT_RATE))
    m.add(Dense(10, activation='softmax', kernel_regularizer=regularizers.l1(L1_RATE)))
    return m

model_l1d, history_l1d, loss_l1d, acc_l1d = run_scenario('2e - L1 + Dropout', build_l1_dropout)

"""## 3. Ringkasan Perbandingan Semua Skenario"""

import pandas as pd

summary = pd.DataFrame({
    'Skenario': ['Base', 'L1', 'L2', 'Dropout', 'Early Stopping', 'L1 + Dropout'],
    'Test Accuracy': [None, acc_l1, acc_l2, acc_dropout, acc_es, acc_l1d],
    'Test Loss': [None, loss_l1, loss_l2, loss_dropout, loss_es, loss_l1d],
})

# Isi baris Base dari hasil evaluasi model1 pada bagian 1
base_loss, base_acc = model1.evaluate(X_test, y_test, verbose=0)
summary.loc[summary['Skenario'] == 'Base', 'Test Accuracy'] = base_acc
summary.loc[summary['Skenario'] == 'Base', 'Test Loss'] = base_loss

summary